# How much to round UI elements (0-3)
roundness = 2

# How wide the border should be around UI elements (0-3)
border_width = 1

# Reduce motion of elements (transitions, hover effects, etc)
reduce_motion = false

# Set the icon theme to use
#icon_theme = breeze-icons

# Set the font family to use
#font_family = sans-serif

# Set the monospace font family to use
#monospace_font_family = monospace