$image = /home/tevildo/wallpaper.png

$background = rgba(131314ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(303031ff)

$inverse_primary = rgba(575f67ff)

$inverse_surface = rgba(e4e2e2ff)

$on_background = rgba(e4e2e2ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(293138ff)

$on_primary_container = rgba(cbd3dcff)

$on_primary_fixed = rgba(151c23ff)

$on_primary_fixed_variant = rgba(40484fff)

$on_secondary = rgba(2e3134ff)

$on_secondary_container = rgba(dee0e4ff)

$on_secondary_fixed = rgba(191c1fff)

$on_secondary_fixed_variant = rgba(44474aff)

$on_surface = rgba(e4e2e2ff)

$on_surface_variant = rgba(c4c7cbff)

$on_tertiary = rgba(362e37ff)

$on_tertiary_container = rgba(dccedaff)

$on_tertiary_fixed = rgba(211922ff)

$on_tertiary_fixed_variant = rgba(4d444eff)

$outline = rgba(8e9195ff)

$outline_variant = rgba(44474aff)

$primary = rgba(bfc7d0ff)

$primary_container = rgba(373f46ff)

$primary_fixed = rgba(dbe3ecff)

$primary_fixed_dim = rgba(bfc7d0ff)

$scrim = rgba(000000ff)

$secondary = rgba(c5c6caff)

$secondary_container = rgba(44474aff)

$secondary_fixed = rgba(e1e2e6ff)

$secondary_fixed_dim = rgba(c5c6caff)

$shadow = rgba(000000ff)

$source_color = rgba(373f46ff)

$surface = rgba(131314ff)

$surface_bright = rgba(393939ff)

$surface_container = rgba(1f1f20ff)

$surface_container_high = rgba(2a2a2aff)

$surface_container_highest = rgba(353535ff)

$surface_container_low = rgba(1b1b1cff)

$surface_container_lowest = rgba(0e0e0fff)

$surface_dim = rgba(131314ff)

$surface_tint = rgba(bfc7d0ff)

$surface_variant = rgba(44474aff)

$tertiary = rgba(d0c2cfff)

$tertiary_container = rgba(443b45ff)

$tertiary_fixed = rgba(eddeebff)

$tertiary_fixed_dim = rgba(d0c2cfff)

