color0 #1c1f21
color1 #fd4663
color2 #98a9b3
color3 #8d96a5
color4 #8f91a3
color5 #b6c2c9
color6 #b8bdc7
color7 #f2f2f3
color8 #646a6e
color9 #fd4663
color10 #98a9b3
color11 #8d96a5
color12 #8f91a3
color13 #b6c2c9
color14 #b8bdc7
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1c1f21
background            #1c1f21
foreground            #f2f2f3
selection_foreground  #b0b3b5
selection_background  #262a2c
active_border_color   #98a9b3
inactive_border_color #262a2c
url_color             #98a9b3
