--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/tevildo/Изображения/wallpapers/wallhaven-x1w8dl.png"

-- Special
background="#121418"
foreground="#e8e5de"
cursor="#e8e5de"

-- Colors
color0="#121418"
color1="#6A736F"
color2="#798377"
color3="#848A7C"
color4="#7B8282"
color5="#9FA295"
color6="#CAC5B4"
color7="#e8e5de"
color8="#a2a09b"
color9="#6A736F"
color10="#798377"
color11="#848A7C"
color12="#7B8282"
color13="#9FA295"
color14="#CAC5B4"
color15="#e8e5de"
