# Shell variables
# Generated by 'wal'
wallpaper="/home/tevildo/Изображения/wallpapers/wallhaven-x1w8dl.png"

# Special
background='#121418'
foreground='#e8e5de'
cursor='#e8e5de'

# Colors
color0='#121418'
color1='#6A736F'
color2='#798377'
color3='#848A7C'
color4='#7B8282'
color5='#9FA295'
color6='#CAC5B4'
color7='#e8e5de'
color8='#a2a09b'
color9='#6A736F'
color10='#798377'
color11='#848A7C'
color12='#7B8282'
color13='#9FA295'
color14='#CAC5B4'
color15='#e8e5de'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
