--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/tevildo/Изображения/wallpapers/sakura.png"

-- Special
background="#02141B"
foreground="#e2e0e1"
cursor="#e2e0e1"

-- Colors
color0="#02141B"
color1="#5A5E64"
color2="#9A5E63"
color3="#757C83"
color4="#808289"
color5="#9D9DA2"
color6="#C1B9BD"
color7="#e2e0e1"
color8="#9e9c9d"
color9="#5A5E64"
color10="#9A5E63"
color11="#757C83"
color12="#808289"
color13="#9D9DA2"
color14="#C1B9BD"
color15="#e2e0e1"
