# Shell variables
# Generated by 'wal'
wallpaper='/home/tevildo/Изображения/wallpapers/wallhaven-vgdlzl.jpg'

# Special
background='#0a0e0f'
foreground='#a5c2c5'
cursor='#a5c2c5'

# Colors
color0='#0a0e0f'
color1='#2B5B64'
color2='#20636E'
color3='#486D74'
color4='#217886'
color5='#4C7B83'
color6='#2A95A2'
color7='#a5c2c5'
color8='#738789'
color9='#2B5B64'
color10='#20636E'
color11='#486D74'
color12='#217886'
color13='#4C7B83'
color14='#2A95A2'
color15='#a5c2c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
