# Shell variables
# Generated by 'wal'
wallpaper='/home/tevildo/Изображения/wallpapers/sakura.png'

# Special
background='#02141B'
foreground='#e2e0e1'
cursor='#e2e0e1'

# Colors
color0='#02141B'
color1='#5A5E64'
color2='#9A5E63'
color3='#757C83'
color4='#808289'
color5='#9D9DA2'
color6='#C1B9BD'
color7='#e2e0e1'
color8='#9e9c9d'
color9='#5A5E64'
color10='#9A5E63'
color11='#757C83'
color12='#808289'
color13='#9D9DA2'
color14='#C1B9BD'
color15='#e2e0e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
