--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/tevildo/Изображения/wallpapers/wallhaven-vgdlzl.jpg"

-- Special
background="#0a0e0f"
foreground="#a5c2c5"
cursor="#a5c2c5"

-- Colors
color0="#0a0e0f"
color1="#2B5B64"
color2="#20636E"
color3="#486D74"
color4="#217886"
color5="#4C7B83"
color6="#2A95A2"
color7="#a5c2c5"
color8="#738789"
color9="#2B5B64"
color10="#20636E"
color11="#486D74"
color12="#217886"
color13="#4C7B83"
color14="#2A95A2"
color15="#a5c2c5"
