# -----------------------------------------------------
# Autostart
# -----------------------------------------------------

$hscripsdir = ~/.config/hypr/scripts

# Setup XDG for screen sharing
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland
exec-once = /usr/lib/xdg-desktop-portal-hyprland

# Start Polkit
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent

# Load GTK settings
exec-once = $hscripsdir/gtk.sh

#exec-once = $hscripsdir/dbus_launch.sh

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Initialize waypaper
exec-once = waypaper --restore

# Launch panel
exec-once = hyprpanel
#exec-once = qs -c noctalia-shell

# KDE connect indicator
exec-once = kdeconnect-indicator

# my soft

exec-once = [workspace 3 silent] Telegram --startintray
#exec-once = $hscripsdir/start_cava.sh
