#source = ~/.config/hypr/conf/decorations/default.conf
#source = ~/.config/hypr/conf/decorations/gamemode.conf
#source = ~/.config/hypr/conf/decorations/no-blur.conf
#source = ~/.config/hypr/conf/decorations/no-rounding.conf
#source = ~/.config/hypr/conf/decorations/no-rounding-more-blur.conf
#source = ~/.config/hypr/conf/decorations/rounding.conf
#source = ~/.config/hypr/conf/decorations/rounding-all-blur.conf
#source = ~/.config/hypr/conf/decorations/rounding-all-blur-no-shadows.conf
#source = ~/.config/hypr/conf/decorations/rounding-more-blur.conf
source = ~/.config/hypr/conf/decorations/custom.conf
