# -----------------------------------------------------
# Layouts
# -----------------------------------------------------

dwindle {
    #pseudotile = true
    preserve_split = true
    smart_split = false
}

master {
    # new_is_master = true
    # new_status = master
}

gestures {
    #workspace_swipe = false
    gesture = 4, horizontal, workspace
}

binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

render {
    direct_scanout = 2
}
