#source = ~/.config/hypr/conf/windows/border-1.conf
#source = ~/.config/hypr/conf/windows/border-1-reverse.conf
#source = ~/.config/hypr/conf/windows/border-2.conf
#source = ~/.config/hypr/conf/windows/border-2-reverse.conf
#source = ~/.config/hypr/conf/windows/border-3.conf
#source = ~/.config/hypr/conf/windows/border-3-reverse.conf
#source = ~/.config/hypr/conf/windows/border-4.conf
#source = ~/.config/hypr/conf/windows/border-4-reverse.conf
#source = ~/.config/hypr/conf/windows/default.conf
#source = ~/.config/hypr/conf/windows/gamemode.conf
#source = ~/.config/hypr/conf/windows/no-border.conf
#source = ~/.config/hypr/conf/windows/no-border-more-gaps.conf
source = ~/.config/hypr/conf/windows/custom.conf
