# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = match:content 1, opacity 1.0 override
windowrule = match:content 2, opacity 1.0 override
windowrule = match:content 3, opacity 1.0 override

$terminal=class ^(kitty)$
windowrule = match:$terminal, opacity 0.9 0.85

windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}

windowrule {
    name = tiled_windows
    match:class = ^(zen|gimp)$
    tile = on
}

windowrule {
    name = floating_settings_windows
    match:class = ^(org.remmina.*|org.pulseaudio.pavucontrol|nm-connection-editor|blueman-manager)$
    float = on
    center = on
    size = 750 450
}

windowrule {
    name = common_senter_large_rules
    match:class = ^(org.kde.kcalc|io.missioncenter.MissionCenter|gjs|waypaper|org.kde.gwenview|com.gitlab.bitseater.meteo|org.cachyos.cachyos-pi|swayimg)$
    float = on
    center = on
    size = 1100 850
}

windowrule {
    name = videoplayers_rules
    match:class = ^(vlc|mpv|io.github.celluloid_player.Celluloid)$
    float = on
    center = on
    size = 1200 850
    opacity = 1.0 override
    no_blur = on
}

windowrule {
    name = telegram
    match:class = ^(org.telegram.desktop)$
    size = 1150 700
    workspace = 3 silent
}

windowrule {
    name = zoom_rules
    match:class = ^(zoom)$
    float = on
    workspace = 2
    opacity = 1.0 override
    # no_shadow = on
    no_blur = on
}

windowrule {
    name = cava_pannel_settings
    match:class = ^(CAVA_PANEL)$
    float = on
    no_initial_focus = on
    border_size = 0
    no_shadow = on
    pin = on
    move = 0 0 
}

windowrule {
    name = zen_no_main_window
    match:class = ^(xdg-desktop-portal-gtk)$
    match:title = .*(имя|файл).*
    float = on
    center = on
    size = 1000 750
    # opacity = 1.0 override
}

windowrule {
    name = telegram_media
    match:class = ^(org.telegram.desktop)$
    match:title = .*Просмотр медиа.*
    float = on
    center = on
}

#windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on

#layerrule = ignorezero, rofi

# layerrule {
#     name = bar
#     match:namespace = ^(bar-0|waybar|notifications-window)$
#     # match:namespace = ^(bar-0|waybar)$

#     blur = on
#     ignore_alpha = 0.5
# }

# layerrule {
#     name = noctalia
#     match:namespace = noctalia-background-.*$
#     # match:namespace = ^(bar-0|waybar)$
#     blur = on
#     ignore_alpha = 0.5
#     blur_popups = on
# }

# layerrule {
#     name = rofi
#     match:namespace = ^(rofi)$
#     blur = on
#     ignore_alpha = 0
# }

layerrule {
    name = ewwbar
    match:namespace = ^eww-bar$
    
    blur = on
    ignore_alpha = 0.4
#    xray = true
}