cursor #dee3e6
cursor_text_color #bfc8cc

foreground            #dee3e6
background            #0f1416
selection_foreground  #1e333b
selection_background  #b3cad4
url_color             #88d1ec

# black
color8   #dee3e6
color0   #dee3e6

# red
color1   #ffb4ab
color9   #ffb4ab

# green
color2   #88d1ec
color10  #88d1ec

# yellow
color3   #b3cad4
color11  #b3cad4

# blue
color4   #c3c3eb
color12  #c3c3eb

# magenta
color5   #88d1ec
color13  #88d1ec

# cyan
color6   #b3cad4
color14  #b3cad4

# white
color15  #dee3e6
color7   #dee3e6

#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#


# # Core Colors
# background            #0f1416
# foreground            #dee3e6
# selection_foreground  #88d1ec
# selection_background  #003543
# cursor                #88d1ec
# cursor_text_color     #0f1416
#
# # Regular Colors
# color0  #0f1416
# color1  #ffb4ab
# color2  #88d1ec
# color3  #c3c3eb
# color4  #b7eaff
# color5  #cfe6f1
# color6  #b3cad4
# color7  #dee3e6
#
# # Bright Colors
# color8  #353a3c
# color9  #ffb4ab
# color10 #88d1ec
# color11 #c3c3eb
# color12 #b7eaff
# color13 #cfe6f1
# color14 #b3cad4
# color15 #dee3e6
