#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#


# Core Colors
background            #131314
foreground            #e4e2e2
selection_foreground  #bfc7d0
selection_background  #293138
cursor                #bfc7d0
cursor_text_color     #cbd3dc

# Regular Colors
color0  #131314
color1  #e4e2e2
color2  #bfc7d0
color3  #373f46
color4  #dbe3ec
color5  #44474a
color6  #44474a
color7  #44474a

# Bright Colors
color8  #393939
color9  #c4c7cb
color10 #bfc7d0
color11 #40484f
color12 #cbd3dc
color13 #dee0e4
color14 #44474a
color15 #44474a
