primary #88d1ec
on_primary #003543
primary_fixed #b7eaff
primary_fixed_dim #88d1ec
on_primary_fixed #001f28
on_primary_fixed_variant #004e61
primary_container #004e61
on_primary_container #b7eaff
inverse_primary #07677f

secondary #b3cad4
secondary_fixed #cfe6f1
secondary_fixed_dim #b3cad4
on_secondary_fixed #071e26
on_secondary_fixed_variant #344a52
secondary_container #344a52
on_secondary_container #cfe6f1

tertiary #c3c3eb
tertiary_fixed #e1e0ff
tertiary_fixed_dim #c3c3eb
on_tertiary_fixed #171837
on_tertiary_fixed_variant #424465
tertiary_container #424465
on_tertiary_container #e1e0ff

error #ffb4ab
error_container #93000a
on_error_container #ffdad6

background #0f1416
on_background #dee3e6
surface #0f1416
surface_bright #353a3c
on_surface #dee3e6
surface_variant #40484c
on_surface_variant #bfc8cc
surface_dim #0f1416
surface_container_lowest #0a0f11
surface_container_low #171c1f
surface_container_high #252b2d
surface_container_highest #303638
inverse_surface #dee3e6
inverse_on_surface #2c3134

source_color #70909d

outline #8a9296
outline_variant #40484c
scrim #000000
shadow #000000
