primary #bfc7d0
on_primary #293138
primary_fixed #dbe3ec
primary_fixed_dim #bfc7d0
on_primary_fixed #151c23
on_primary_fixed_variant #40484f
primary_container #373f46
on_primary_container #cbd3dc
inverse_primary #575f67

secondary #c5c6ca
secondary_fixed #e1e2e6
secondary_fixed_dim #c5c6ca
on_secondary_fixed #191c1f
on_secondary_fixed_variant #44474a
secondary_container #44474a
on_secondary_container #dee0e4

tertiary #d0c2cf
tertiary_fixed #eddeeb
tertiary_fixed_dim #d0c2cf
on_tertiary_fixed #211922
on_tertiary_fixed_variant #4d444e
tertiary_container #443b45
on_tertiary_container #dcceda

error #ffb4ab
error_container #93000a
on_error_container #ffdad6

background #131314
on_background #e4e2e2
surface #131314
surface_bright #393939
on_surface #e4e2e2
surface_variant #44474a
on_surface_variant #c4c7cb
surface_dim #131314
surface_container_lowest #0e0e0f
surface_container_low #1b1b1c
surface_container_high #2a2a2a
surface_container_highest #353535
inverse_surface #e4e2e2
inverse_on_surface #303031

source_color #373f46

outline #8e9195
outline_variant #44474a
scrim #000000
shadow #000000
