decoration {

    rounding = 6
    rounding_power = 4
    active_opacity = 0.95
    inactive_opacity = 0.85
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 8#12#6
        passes = 3#6#2
        #size = 12
        passes = 6
        new_optimizations = true
        ignore_opacity = false
        xray = true
        #noise = 0.0117
        #contrast = 0.8916
        #brightness = 0.8172
        #vibrancy = 0.1696
        popups = true
        # blurls = waybar
    }

    shadow {
        enabled = true
        range = 30
        render_power = 3
        color = 0x66000000
        #color = 0xee1a1a1a
    }

    #drop_shadow = true
    #shadow_range = 30
    #shadow_render_power = 3
    #col.shadow = 0x66000000
}

#layerrule = blur, bar-0
